lmb-997: downgrade ember-data to 5.3.8
Error: Could not find module `@glimmer/runtime` imported from `(require)`
    at missingModule (loader.js:247:1)
    at findModule (loader.js:258:1)
    at requireModule (loader.js:24:1)
    at Object.require (<anonymous>:9754:14)
    at InElementSupportProvider.require (<anonymous>:5759:80)
    at new InElementSupportProvider (<anonymous>:5529:27)
    at new RenderTree (<anonymous>:5783:33)
    at _class.init (<anonymous>:10456:42)
    at new BaseObject (<anonymous>:9484:12)
    at new _default (<anonymous>:818:7)